name: Quality-Checks

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    quality-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install Dependencies
              run: npm i --ignore-scripts

            - name: Check Prettier adherence
              run: npm run prettier:check
              if: ${{ always() }}

            - name: Run linter
              run: npm run lint
              if: ${{ always() }}

            - name: Run TS
              run: npm run ts:check
              if: ${{ always() }}

            - name: Run unit tests
              run: npm run test
              if: ${{ always() }}

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
